<?php

/**
 * ProcessWire Remove Heights Textformatter
 *
 *
 *
 */

class TextformatterRemoveHeights extends Textformatter {

	public static function getModuleInfo() {
		return array(
			'title' => 'Remove Heights Textformatter',
			'version' => 101,
			'summary' => "removes the Height attribute from image tags",
			'href' => '',
		);
	}

	public function format(&$str) {

		$dom = new DOMDocument();
		$dom->loadHTML(mb_convert_encoding($str, 'HTML-ENTITIES', 'UTF-8'), LIBXML_HTML_NOIMPLIED | LIBXML_HTML_NODEFDTD);
		$dom->preserveWhiteSpace = false;
		$images = $dom->getElementsByTagName('img');

		foreach ($images as $image) {
			$image->removeAttribute('height');
	    	}

		$str = $dom->saveHTML();

	}
}
